swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /jieba

securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: authorization
  # AdminSecurity:
  #   type: apiKey
  #   in: header
  #   name: ADMIN-API-KEY
  # MediaSecurity:
  #   type: apiKey
  #   in: header
  #   name: SIMPLE-API-KEY
# securityDefinitions:
#   api_key:
#     type: apiKey
#     name: api_key
#     in: header

#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
# consumes:
#   - application/json
# format of the responses to the client (Accepts)
# produces:
#   - application/json

security:
  - Authorization: [] 
  
paths:
  /cuts:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: cuts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

        - name: models
          in: query
          description: cut模式
          required: false
          type: boolean

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cutAll:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: cutAll
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cutHMM:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: cutHMM
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cutForSearch:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: cutForSearch
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cutSmall:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: cutSmall
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tag:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: tag
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /extract:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: extract
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

        - name: topN
          in: query
          description: topN
          required: false
          type: integer

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /insertWord:
    # binds a127 app logic to a route
    x-swagger-router-controller: jieba_api
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: insertWord
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: words
          in: body
          description: 要分詞的文字
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CutWordsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  CutWordsResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
